In [1]:
import csv
from gensim.models.word2vec import Word2Vec
import pandas as pd
import numpy as np
from keras.utils import np_utils
from keras.preprocessing.text import Tokenizer
from collections import Counter

In [2]:
df_w2v = pd.read_csv('kyrbs2019_W2V.csv')
df_w2v.drop(columns = 'Unnamed: 0', axis = 1 ,inplace = True)

In [3]:
df_w2v

,PR_HT,F_BR,F_FRUIT,F_SODA,F_CAFFEINE,F_SWDRINK,F_FASTFOOD,F_VEG,F_MILK,F_EDU,...,E_LT_M,E_LT_SM,E_EDU_F,E_KRN_F,E_BORN_F,E_EDU_M,E_KRN_M,E_BORN_M,SleepAvg_WK,BMI
0,PR_HT_4,F_BR_2,F_FRUIT_3,F_SODA_2,F_CAFFEINE_1,F_SWDRINK_2,F_FASTFOOD_3,F_VEG_2,F_MILK_2,F_EDU_2,...,E_LT_M_1,E_LT_SM_9999,E_EDU_F_3,E_KRN_F_1,E_BORN_F_9999,E_EDU_M_3,E_KRN_M_1,E_BORN_M_9999,SleepAvg_WK_8,BMI_0
1,PR_HT_3,F_BR_4,F_FRUIT_7,F_SODA_3,F_CAFFEINE_1,F_SWDRINK_1,F_FASTFOOD_1,F_VEG_1,F_MILK_4,F_EDU_2,...,E_LT_M_8888,E_LT_SM_8888,E_EDU_F_8888,E_KRN_F_8888,E_BORN_F_8888,E_EDU_M_8888,E_KRN_M_8888,E_BORN_M_8888,SleepAvg_WK_5,BMI_0
2,PR_HT_1,F_BR_1,F_FRUIT_7,F_SODA_1,F_CAFFEINE_1,F_SWDRINK_1,F_FASTFOOD_2,F_VEG_3,F_MILK_2,F_EDU_1,...,E_LT_M_1,E_LT_SM_9999,E_EDU_F_2,E_KRN_F_1,E_BORN_F_9999,E_EDU_M_3,E_KRN_M_1,E_BORN_M_9999,SleepAvg_WK_14,BMI_1
3,PR_HT_3,F_BR_4,F_FRUIT_6,F_SODA_1,F_CAFFEINE_1,F_SWDRINK_1,F_FASTFOOD_1,F_VEG_6,F_MILK_3,F_EDU_1,...,E_LT_M_8888,E_LT_SM_8888,E_EDU_F_8888,E_KRN_F_8888,E_BORN_F_8888,E_EDU_M_8888,E_KRN_M_8888,E_BORN_M_8888,SleepAvg_WK_7,BMI_1
4,PR_HT_1,F_BR_8,F_FRUIT_6,F_SODA_2,F_CAFFEINE_2,F_SWDRINK_2,F_FASTFOOD_1,F_VEG_7,F_MILK_3,F_EDU_2,...,E_LT_M_8888,E_LT_SM_8888,E_EDU_F_8888,E_KRN_F_8888,E_BORN_F_8888,E_EDU_M_8888,E_KRN_M_8888,E_BORN_M_8888,SleepAvg_WK_19,BMI_1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27695,PR_HT_1,F_BR_1,F_FRUIT_2,F_SODA_1,F_CAFFEINE_1,F_SWDRINK_2,F_FASTFOOD_1,F_VEG_7,F_MILK_5,F_EDU_1,...,E_LT_M_1,E_LT_SM_9999,E_EDU_F_4,E_KRN_F_1,E_BORN_F_9999,E_EDU_M_4,E_KRN_M_2,E_BORN_M_5,SleepAvg_WK_10,BMI_1
27696,PR_HT_3,F_BR_7,F_FRUIT_2,F_SODA_1,F_CAFFEINE_2,F_SWDRINK_2,F_FASTFOOD_3,F_VEG_4,F_MILK_5,F_EDU_2,...,E_LT_M_8888,E_LT_SM_8888,E_EDU_F_8888,E_KRN_F_8888,E_BORN_F_8888,E_EDU_M_8888,E_KRN_M_8888,E_BORN_M_8888,SleepAvg_WK_8,BMI_0
27697,PR_HT_2,F_BR_8,F_FRUIT_3,F_SODA_2,F_CAFFEINE_2,F_SWDRINK_4,F_FASTFOOD_2,F_VEG_4,F_MILK_5,F_EDU_1,...,E_LT_M_1,E_LT_SM_9999,E_EDU_F_2,E_KRN_F_1,E_BORN_F_9999,E_EDU_M_2,E_KRN_M_1,E_BORN_M_9999,SleepAvg_WK_8,BMI_1
27698,PR_HT_1,F_BR_8,F_FRUIT_2,F_SODA_2,F_CAFFEINE_1,F_SWDRINK_2,F_FASTFOOD_2,F_VEG_2,F_MILK_4,F_EDU_1,...,E_LT_M_1,E_LT_SM_9999,E_EDU_F_2,E_KRN_F_1,E_BORN_F_9999,E_EDU_M_2,E_KRN_M_1,E_BORN_M_9999,SleepAvg_WK_8,BMI_0
27699,PR_HT_2,F_BR_1,F_FRUIT_2,F_SODA_5,F_CAFFEINE_2,F_SWDRINK_5,F_FASTFOOD_2,F_VEG_2,F_MILK_5,F_EDU_1,...,E_LT_M_1,E_LT_SM_9999,E_EDU_F_3,E_KRN_F_1,E_BORN_F_9999,E_EDU_M_3,E_KRN_M_1,E_BORN_M_9999,SleepAvg_WK_7,BMI_0

In [4]:
'BMI' in df_w2v.columns

True

In [5]:
'HT' in df_w2v.columns

False

In [6]:
'WT' in df_w2v.columns

False

In [7]:
df_w2v.shape

(27700, 157)

In [8]:
a = df_w2v[['BMI']]
b = df_w2v.drop(['BMI'], axis = 1)

In [9]:
b.insert(78, 'BMI',a)

In [10]:
df = pd.DataFrame(b)

In [11]:
df

,PR_HT,F_BR,F_FRUIT,F_SODA,F_CAFFEINE,F_SWDRINK,F_FASTFOOD,F_VEG,F_MILK,F_EDU,...,E_LT_SF,E_LT_M,E_LT_SM,E_EDU_F,E_KRN_F,E_BORN_F,E_EDU_M,E_KRN_M,E_BORN_M,SleepAvg_WK
0,PR_HT_4,F_BR_2,F_FRUIT_3,F_SODA_2,F_CAFFEINE_1,F_SWDRINK_2,F_FASTFOOD_3,F_VEG_2,F_MILK_2,F_EDU_2,...,E_LT_SF_9999,E_LT_M_1,E_LT_SM_9999,E_EDU_F_3,E_KRN_F_1,E_BORN_F_9999,E_EDU_M_3,E_KRN_M_1,E_BORN_M_9999,SleepAvg_WK_8
1,PR_HT_3,F_BR_4,F_FRUIT_7,F_SODA_3,F_CAFFEINE_1,F_SWDRINK_1,F_FASTFOOD_1,F_VEG_1,F_MILK_4,F_EDU_2,...,E_LT_SF_8888,E_LT_M_8888,E_LT_SM_8888,E_EDU_F_8888,E_KRN_F_8888,E_BORN_F_8888,E_EDU_M_8888,E_KRN_M_8888,E_BORN_M_8888,SleepAvg_WK_5
2,PR_HT_1,F_BR_1,F_FRUIT_7,F_SODA_1,F_CAFFEINE_1,F_SWDRINK_1,F_FASTFOOD_2,F_VEG_3,F_MILK_2,F_EDU_1,...,E_LT_SF_9999,E_LT_M_1,E_LT_SM_9999,E_EDU_F_2,E_KRN_F_1,E_BORN_F_9999,E_EDU_M_3,E_KRN_M_1,E_BORN_M_9999,SleepAvg_WK_14
3,PR_HT_3,F_BR_4,F_FRUIT_6,F_SODA_1,F_CAFFEINE_1,F_SWDRINK_1,F_FASTFOOD_1,F_VEG_6,F_MILK_3,F_EDU_1,...,E_LT_SF_8888,E_LT_M_8888,E_LT_SM_8888,E_EDU_F_8888,E_KRN_F_8888,E_BORN_F_8888,E_EDU_M_8888,E_KRN_M_8888,E_BORN_M_8888,SleepAvg_WK_7
4,PR_HT_1,F_BR_8,F_FRUIT_6,F_SODA_2,F_CAFFEINE_2,F_SWDRINK_2,F_FASTFOOD_1,F_VEG_7,F_MILK_3,F_EDU_2,...,E_LT_SF_8888,E_LT_M_8888,E_LT_SM_8888,E_EDU_F_8888,E_KRN_F_8888,E_BORN_F_8888,E_EDU_M_8888,E_KRN_M_8888,E_BORN_M_8888,SleepAvg_WK_19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27695,PR_HT_1,F_BR_1,F_FRUIT_2,F_SODA_1,F_CAFFEINE_1,F_SWDRINK_2,F_FASTFOOD_1,F_VEG_7,F_MILK_5,F_EDU_1,...,E_LT_SF_9999,E_LT_M_1,E_LT_SM_9999,E_EDU_F_4,E_KRN_F_1,E_BORN_F_9999,E_EDU_M_4,E_KRN_M_2,E_BORN_M_5,SleepAvg_WK_10
27696,PR_HT_3,F_BR_7,F_FRUIT_2,F_SODA_1,F_CAFFEINE_2,F_SWDRINK_2,F_FASTFOOD_3,F_VEG_4,F_MILK_5,F_EDU_2,...,E_LT_SF_8888,E_LT_M_8888,E_LT_SM_8888,E_EDU_F_8888,E_KRN_F_8888,E_BORN_F_8888,E_EDU_M_8888,E_KRN_M_8888,E_BORN_M_8888,SleepAvg_WK_8
27697,PR_HT_2,F_BR_8,F_FRUIT_3,F_SODA_2,F_CAFFEINE_2,F_SWDRINK_4,F_FASTFOOD_2,F_VEG_4,F_MILK_5,F_EDU_1,...,E_LT_SF_9999,E_LT_M_1,E_LT_SM_9999,E_EDU_F_2,E_KRN_F_1,E_BORN_F_9999,E_EDU_M_2,E_KRN_M_1,E_BORN_M_9999,SleepAvg_WK_8
27698,PR_HT_1,F_BR_8,F_FRUIT_2,F_SODA_2,F_CAFFEINE_1,F_SWDRINK_2,F_FASTFOOD_2,F_VEG_2,F_MILK_4,F_EDU_1,...,E_LT_SF_9999,E_LT_M_1,E_LT_SM_9999,E_EDU_F_2,E_KRN_F_1,E_BORN_F_9999,E_EDU_M_2,E_KRN_M_1,E_BORN_M_9999,SleepAvg_WK_8
27699,PR_HT_2,F_BR_1,F_FRUIT_2,F_SODA_5,F_CAFFEINE_2,F_SWDRINK_5,F_FASTFOOD_2,F_VEG_2,F_MILK_5,F_EDU_1,...,E_LT_SF_9999,E_LT_M_1,E_LT_SM_9999,E_EDU_F_3,E_KRN_F_1,E_BORN_F_9999,E_EDU_M_3,E_KRN_M_1,E_BORN_M_9999,SleepAvg_WK_7

In [12]:
df.BMI.value_counts()

BMI_0    21982
BMI_1     5718
Name: BMI, dtype: int64

## W2V 모델에 넣기 좋게 리스트 형식으로 변환

In [13]:
df_list  = df.values.tolist()

In [14]:
len(df_list)

27700

### 토크나이징

In [15]:
def tokenize(corpus):
    """
    Tokenize the corpus of text.
    :param corpus: list containing a string of text (example: ["I like playing football with my friends"])
    :return corpus_tokenized: indexed list of words in the corpus, in the same order as the original corpus (the example above would return [[1, 2, 3, 4]])
    :return V: size of vocabulary
    """
    tokenizer = Tokenizer()
    tokenizer.fit_on_texts(corpus)
    corpus_tokenized = tokenizer.texts_to_sequences(corpus)
    V = len(tokenizer.word_index)
    return corpus_tokenized, V

In [16]:
cor, V = tokenize(df_list)
V

726

## 모델 훈련

In [17]:
model_sg = Word2Vec(df_list, workers = 6, min_count = 1, window = 156, sg = 1)

In [18]:
# 모델 저장
model_sg.save('model_sg.model')

## 유사 클러스터링

In [19]:
#create Vocab dict
cols = []
for j in df.columns:
    target = df[j].unique()
    for i in target:
        cols.append(i)

In [20]:
len(cols)

726

In [21]:
cols

['PR_HT_4',
 'PR_HT_3',
 'PR_HT_1',
 'PR_HT_2',
 'PR_HT_5',
 'F_BR_2',
 'F_BR_4',
 'F_BR_1',
 'F_BR_8',
 'F_BR_6',
 'F_BR_5',
 'F_BR_3',
 'F_BR_7',
 'F_FRUIT_3',
 'F_FRUIT_7',
 'F_FRUIT_6',
 'F_FRUIT_2',
 'F_FRUIT_1',
 'F_FRUIT_4',
 'F_FRUIT_5',
 'F_SODA_2',
 'F_SODA_3',
 'F_SODA_1',
 'F_SODA_4',
 'F_SODA_5',
 'F_SODA_6',
 'F_SODA_7',
 'F_CAFFEINE_1',
 'F_CAFFEINE_2',
 'F_CAFFEINE_3',
 'F_CAFFEINE_5',
 'F_CAFFEINE_4',
 'F_CAFFEINE_6',
 'F_CAFFEINE_7',
 'F_SWDRINK_2',
 'F_SWDRINK_1',
 'F_SWDRINK_3',
 'F_SWDRINK_5',
 'F_SWDRINK_4',
 'F_SWDRINK_7',
 'F_SWDRINK_6',
 'F_FASTFOOD_3',
 'F_FASTFOOD_1',
 'F_FASTFOOD_2',
 'F_FASTFOOD_4',
 'F_FASTFOOD_6',
 'F_FASTFOOD_7',
 'F_FASTFOOD_5',
 'F_VEG_2',
 'F_VEG_1',
 'F_VEG_3',
 'F_VEG_6',
 'F_VEG_7',
 'F_VEG_5',
 'F_VEG_4',
 'F_MILK_2',
 'F_MILK_4',
 'F_MILK_3',
 'F_MILK_5',
 'F_MILK_1',
 'F_MILK_7',
 'F_MILK_6',
 'F_EDU_2',
 'F_EDU_1',
 'F_CS_4',
 'F_CS_2',
 'F_CS_1',
 'F_CS_3',
 'F_CS_7',
 'F_CS_5',
 'F_CS_6',
 'F_CS_F01_9999',
 'F_CS_F01_1',
 'F_CS_F02_9999',
 'F_CS_F02_2',
 'F_CS_F03_9999',
 'F_CS_F03_3',
 'F_CS_F04_4',
 'F_CS_F04_9999',
 'F_CS_F05_9999',
 'F_CS_F05_5',
 'F_CS_F06_9999',
 'F_CS_F06_6',
 'F_CS_F07_7',
 'F_CS_F07_9999',
 'F_CS_F08_9999',
 'F_CS_F08_8',
 'F_CS_F09_9999',
 'F_CS_F09_9',
 'F_CS_F10_10',
 'F_CS_F10_9999',
 'F_CS_F11_9999',
 'F_CS_F11_11',
 'F_CS_F12_9999',
 'F_CS_F12_12',
 'F_WAT_5',
 'F_WAT_3',
 'F_WAT_2',
 'F_WAT_4',
 'F_WAT_1',
 'PA_TOT_2',
 'PA_TOT_4',
 'PA_TOT_5',
 'PA_TOT_6',
 'PA_TOT_1',
 'PA_TOT_3',
 'PA_TOT_8',
 'PA_TOT_7',
 'PA_VIG_1',
 'PA_VIG_2',
 'PA_VIG_4',
 'PA_VIG_3',
 'PA_VIG_6',
 'PA_VIG_5',
 'PA_MSC_2',
 'PA_MSC_1',
 'PA_MSC_5',
 'PA_MSC_3',
 'PA_MSC_6',
 'PA_MSC_4',
 'PA_WLK_8',
 'PA_WLK_1',
 'PA_WLK_7',
 'PA_WLK_5',
 'PA_WLK_6',
 'PA_WLK_2',
 'PA_WLK_4',
 'PA_WLK_3',
 'PA_WLK_MM_1',
 'PA_WLK_MM_0',
 'PA_WLK_MM_4',
 'PA_WLK_MM_2',
 'PA_WLK_MM_3',
 'PA_SWD_S_7',
 'PA_SWD_S_2',
 'PA_SWD_S_10',
 'PA_SWD_S_8',
 'PA_SWD_S_14',
 'PA_SWD_S_0',
 'PA_SWD_S_1',
 'PA_SWD_S_5',
 'PA_SWD_S_6',
 'PA_SWD_S_3',
 'PA_SWD_S_9',
 'PA_SWD_S_11',
 'PA_SWD_S_4',
 'PA_SWD_S_12',
 'PA_SWD_S_13',
 'PA_SWD_N_4',
 'PA_SWD_N_5',
 'PA_SWD_N_3',
 'PA_SWD_N_1',
 'PA_SWD_N_2',
 'PA_SWD_N_0',
 'PA_SWD_N_7',
 'PA_SWD_N_6',
 'PA_SWK_S_0',
 'PA_SWK_S_11',
 'PA_SWK_S_2',
 'PA_SWK_S_1',
 'PA_SWK_S_5',
 'PA_SWK_S_4',
 'PA_SWK_S_6',
 'PA_SWK_S_3',
 'PA_SWK_S_7',
 'PA_SWK_S_8',
 'PA_SWK_S_10',
 'PA_SWK_S_9',
 'PA_SWK_N_10',
 'PA_SWK_N_1',
 'PA_SWK_N_5',
 'PA_SWK_N_6',
 'PA_SWK_N_2',
 'PA_SWK_N_8',
 'PA_SWK_N_3',
 'PA_SWK_N_4',
 'PA_SWK_N_0',
 'PA_SWK_N_7',
 'PA_SWK_N_12',
 'PA_SWK_N_9',
 'PA_SWK_N_11',
 'PA_PE_FQ_1',
 'PA_PE_FQ_4',
 'PA_PE_FQ_2',
 'PA_PE_FQ_3',
 'PA_ST_1',
 'PA_ST_3',
 'PA_ST_2',
 'PA_ST_5',
 'PA_ST_4',
 'PA_TRA_1',
 'PA_TRA_8',
 'PA_TRA_6',
 'PA_TRA_4',
 'PA_TRA_2',
 'PA_TRA_5',
 'PA_TRA_3',
 'PA_TRA_7',
 'PA_TRA_MM_0',
 'PA_TRA_MM_3',
 'PA_TRA_MM_2',
 'PA_TRA_MM_1',
 'WC_MN_3',
 'WC_MN_1',
 'WC_MN_4',
 'WC_MN_2',
 'WC_MN_M01_0',
 'WC_MN_M01_9999',
 'WC_MN_M01_1',
 'WC_MN_M02_0',
 'WC_MN_M02_9999',
 'WC_MN_M02_1',
 'WC_MN_M03_0',
 'WC_MN_M03_9999',
 'WC_MN_M03_1',
 'WC_MN_M04_0',
 'WC_MN_M04_9999',
 'WC_MN_M04_1',
 'WC_MN_M05_0',
 'WC_MN_M05_9999',
 'WC_MN_M05_1',
 'WC_MN_M06_0',
 'WC_MN_M06_9999',
 'WC_MN_M06_1',
 'WC_MN_M07_0',
 'WC_MN_M07_9999',
 'WC_MN_M07_1',
 'WC_MN_M08_0',
 'WC_MN_M08_9999',
 'WC_MN_M08_1',
 'WC_MN_M09_0',
 'WC_MN_M09_9999',
 'WC_MN_M09_1',
 'WC_MN_M10_0',
 'WC_MN_M10_9999',
 'WC_MN_M10_1',
 'M_STR_3',
 'M_STR_2',
 'M_STR_4',
 'M_STR_5',
 'M_STR_1',
 'M_SLP_EN_4',
 'M_SLP_EN_1',
 'M_SLP_EN_5',
 'M_SLP_EN_3',
 'M_SLP_EN_2',
 'M_SAD_1',
 'M_SAD_2',
 'M_SUI_CON_1',
 'M_SUI_CON_2',
 'M_SUI_PLN_1',
 'M_SUI_PLN_2',
 'M_SUI_ATT_1',
 'M_SUI_ATT_2',
 'O_BR_FQ_4',
 'O_BR_FQ_3',
 'O_BR_FQ_7',
 'O_BR_FQ_10',
 'O_BR_FQ_5',
 'O_BR_FQ_2',
 'O_BR_FQ_1',
 'O_BR_FQ_6',
 'O_BR_FQ_8',
 'O_BR_FQ_9',
 'O_BR_SLP_2',
 'O_BR_SLP_1',
 'O_BR_SLP_3',
 'O_BR_S_4',
 'O_BR_S_3',
 'O_BR_S_2',
 'O_BR_S_1',
 'O_OCP1_1',
 'O_OCP1_9999',
 'O_OCP2_9999',
 'O_OCP2_2',
 'O_OCP3_9999',
 'O_OCP3_3',
 'O_OCP4_9999',
 'O_OCP4_4',
 'O_OCP5_9999',
 'O_OCP5_5',
 'O_DC_FQ_2',
 'O_DC_FQ_3',
 'O_DC_FQ_1',
 'O_DC_FQ_5',
 'O_DC_FQ_4',
 'O_SLNT_1',
 'O_SLNT_2',
 'O_SCL_1',
 'O_SCL_2',
 'PR_OH_3',
 'PR_OH_1',
 'PR_OH_2',
 'PR_OH_4',
 'PR_OH_5',
 'O_SYMP1_1',
 'O_SYMP1_0',
 'O_SYMP1_1_2',
 'O_SYMP1_1_0',
 'O_SYMP1_1_1',
 'O_SYMP2_0',
 'O_SYMP2_1',
 'O_SYMP3_0',
 'O_SYMP3_1',
 'O_SYMP4_0',
 'O_SYMP4_1',
 'O_SYMP5_0',
 'O_SYMP5_1',
 'O_SYMP6_0',
 'O_SYMP6_1',
 'O_EDU_1',
 'O_EDU_2',
 'HW_SPML_S_3',
 'HW_SPML_S_1',
 'HW_SPML_S_2',
 'HW_SPML_S_4',
 'HW_SPRM_S_1',
 'HW_SPRM_S_2',
 'HW_SPRM_S_3',
 'HW_SPRM_S_4',
 'HW_SPML_H_2',
 'HW_SPML_H_1',
 'HW_SPML_H_3',
 'HW_SPML_H_4',
 'HW_SPRM_H_2',
 'HW_SPRM_H_1',
 'HW_SPRM_H_3',
 'HW_SPRM_H_4',
 'BMI_0',
 'BMI_1',
 'HW_SPGO_H_2',
 'HW_SPGO_H_1',
 'HW_SPGO_H_3',
 'HW_SPGO_H_4',
 'HW_S_R_2',
 'HW_S_R_1',
 'HW_S_R_7',
 'HW_S_R_9',
 'HW_S_R_5',
 'HW_S_R_4',
 'HW_S_R_10',
 'HW_S_R_8',
 'HW_S_R_3',
 'HW_S_R_6',
 'HW_EDU_1',
 'HW_EDU_2',
 'I_SB_FR_1',
 'I_SB_FR_2',
 'I_SB_FR_3',
 'I_SB_FR_4',
 'I_SB_FR_5',
 'I_SB_BK_5',
 'I_SB_BK_2',
 'I_SB_BK_3',
 'I_SB_BK_4',
 'I_SB_BK_1',
 'I_SB_EX_5',
 'I_SB_EX_2',
 'I_SB_EX_4',
 'I_SB_EX_3',
 'I_SB_EX_1',
 'I_SCH_TRT_1',
 'I_SCH_TRT_2',
 'I_SCH_ED1_1',
 'I_SCH_ED1_9999',
 'I_SCH_ED2_9999',
 'I_SCH_ED2_2',
 'I_SCH_ED3_9999',
 'I_SCH_ED3_3',
 'I_SCH_ED4_9999',
 'I_SCH_ED4_4',
 'I_SCH_ED5_9999',
 'I_SCH_ED5_5',
 'V_TRT_1',
 'V_TRT_3',
 'V_TRT_2',
 'V_TRT_4',
 'V_TRT_5',
 'V_TRT_7',
 'V_TRT_6',
 'AC_LT_2',
 'AC_LT_1',
 'AC_FAGE_9',
 'AC_FAGE_14',
 'AC_FAGE_8',
 'AC_FAGE_1',
 'AC_FAGE_10',
 'AC_FAGE_7',
 'AC_FAGE_11',
 'AC_FAGE_2',
 'AC_FAGE_3',
 'AC_FAGE_12',
 'AC_FAGE_13',
 'AC_FAGE_4',
 'AC_FAGE_5',
 'AC_FAGE_6',
 'AC_DAYS_4',
 'AC_DAYS_0',
 'AC_DAYS_1',
 'AC_DAYS_3',
 'AC_DAYS_2',
 'AC_DAYS_6',
 'AC_DAYS_5',
 'AC_DAYS_7',
 'AC_AMNT_4',
 'AC_AMNT_0',
 'AC_AMNT_5',
 'AC_AMNT_1',
 'AC_AMNT_2',
 'AC_AMNT_3',
 'AC_DRUNK_1',
 'AC_DRUNK_0',
 'AC_DRUNK_4',
 'AC_DRUNK_2',
 'AC_DRUNK_3',
 'AC_ACCESS_5',
 'AC_ACCESS_1',
 'AC_ACCESS_4',
 'AC_ACCESS_2',
 'AC_ACCESS_3',
 'TC_LT_2',
 'TC_LT_1',
 'TC_DAYS_7',
 'TC_DAYS_0',
 'TC_DAYS_5',
 'TC_DAYS_6',
 'TC_DAYS_4',
 'TC_DAYS_1',
 'TC_DAYS_3',
 'TC_DAYS_2',
 'TC_EC_LT_1',
 'TC_EC_LT_2',
 'TC_EC_MN_0',
 'TC_EC_MN_3',
 'TC_EC_MN_1',
 'TC_EC_MN_7',
 'TC_EC_MN_2',
 'TC_EC_MN_5',
 'TC_EC_MN_4',
 'TC_EC_MN_6',
 'TC_HTP_LT_1',
 'TC_HTP_LT_2',
 'TC_HTP_MN_0',
 'TC_HTP_MN_1',
 'TC_HTP_MN_3',
 'TC_HTP_MN_4',
 'TC_HTP_MN_2',
 'TC_HTP_MN_7',
 'TC_HTP_MN_6',
 'TC_HTP_MN_5',
 'TC_FAGE_10',
 'TC_FAGE_14',
 'TC_FAGE_9',
 'TC_FAGE_11',
 'TC_FAGE_8',
 'TC_FAGE_6',
 'TC_FAGE_7',
 'TC_FAGE_12',
 'TC_FAGE_5',
 'TC_FAGE_3',
 'TC_FAGE_4',
 'TC_FAGE_13',
 'TC_FAGE_1',
 'TC_FAGE_2',
 'TC_DAGE_10',
 'TC_DAGE_11',
 'TC_DAGE_9999',
 'TC_DAGE_12',
 'TC_DAGE_9',
 'TC_DAGE_8',
 'TC_DAGE_13',
 'TC_DAGE_7',
 'TC_DAGE_4',
 'TC_DAGE_1',
 'TC_DAGE_6',
 'TC_DAGE_2',
 'TC_DAGE_5',
 'TC_DAGE_3',
 'TC_AMNT_5',
 'TC_AMNT_3',
 'TC_AMNT_0',
 'TC_AMNT_2',
 'TC_AMNT_4',
 'TC_AMNT_6',
 'TC_AMNT_1',
 'TC_ACCESS_5',
 'TC_ACCESS_1',
 'TC_ACCESS_4',
 'TC_ACCESS_3',
 'TC_ACCESS_2',
 'TC_QT_YR_1',
 'TC_QT_YR_2',
 'TC_QT_YR_9999',
 'TC_SND_H_1',
 'TC_SND_H_4',
 'TC_SND_H_3',
 'TC_SND_H_8',
 'TC_SND_H_2',
 'TC_SND_H_6',
 'TC_SND_H_7',
 'TC_SND_H_5',
 'TC_SND_S_1',
 'TC_SND_S_3',
 'TC_SND_S_8',
 'TC_SND_S_4',
 'TC_SND_S_2',
 'TC_SND_S_5',
 'TC_SND_S_6',
 'TC_SND_S_7',
 'TC_SND_P_2',
 'TC_SND_P_1',
 'TC_SND_P_3',
 'TC_SND_P_8',
 'TC_SND_P_4',
 'TC_SND_P_5',
 'TC_SND_P_7',
 'TC_SND_P_6',
 'TC_GHW_2',
 'TC_GHW_1',
 'TC_GHW_H_1',
 'TC_GHW_H_9999',
 'TC_GHW_H_4',
 'TC_GHW_H_3',
 'TC_GHW_H_2',
 'TC_GHW_QT_1',
 'TC_GHW_QT_9999',
 'TC_GHW_QT_4',
 'TC_GHW_QT_3',
 'TC_GHW_QT_2',
 'S_SI_2',
 'S_SI_1',
 'S_CONT_4',
 'S_CONT_1',
 'S_CONT_9999',
 'S_CONT_2',
 'S_CONT_3',
 'S_CONT_M_9999',
 'S_CONT_M_2',
 'S_CONT_M_3',
 'S_CONT_M_1',
 'S_CONT_M_5',
 'S_CONT_M_4',
 'S_CONT_M_6',
 'S_EDU_2',
 'S_EDU_1',
 'DR_EXP_1',
 'DR_EXP_2',
 'DR_LT_0',
 'DR_LT_1',
 'DR_LT_3',
 'DR_LT_2',
 'AS_DG_LT_1',
 'AS_DG_LT_2',
 'AS_DG_YR_0',
 'AS_DG_YR_2',
 'AS_DG_YR_1',
 'RH_DG_LT_1',
 'RH_DG_LT_2',
 'RH_DG_YR_9999',
 'RH_DG_YR_2',
 'RH_DG_YR_1',
 'ECZ_DG_LT_1',
 'ECZ_DG_LT_2',
 'ECZ_DG_YR_9999',
 'ECZ_DG_YR_1',
 'ECZ_DG_YR_2',
 'INT_WD_2',
 'INT_WD_1',
 'INT_WD_MM_2',
 'INT_WD_MM_0',
 'INT_WD_MM_4',
 'INT_WD_MM_3',
 'INT_WD_MM_5',
 'INT_WD_MM_1',
 'INT_WK_2',
 'INT_WK_1',
 'INT_WK_MM_4',
 'INT_WK_MM_0',
 'INT_WK_MM_5',
 'INT_WK_MM_8',
 'INT_WK_MM_3',
 'INT_WK_MM_10',
 'INT_WK_MM_2',
 'INT_WK_MM_1',
 'INT_WK_MM_7',
 'INT_WK_MM_6',
 'INT_WK_MM_9',
 'AGE_16',
 'AGE_15',
 'AGE_17',
 'AGE_18',
 'AGE_13',
 'AGE_12',
 'AGE_14',
 'E_S_RCRD_5',
 'E_S_RCRD_3',
 'E_S_RCRD_2',
 'E_S_RCRD_4',
 'E_S_RCRD_1',
 'E_SES_3',
 'E_SES_4',
 'E_SES_2',
 'E_SES_5',
 'E_SES_1',
 'E_RES_1',
 'E_RES_3',
 'E_RES_5',
 'E_RES_4',
 'E_RES_2',
 'GRADE_4',
 'GRADE_5',
 'GRADE_6',
 'GRADE_1',
 'GRADE_2',
 'GRADE_3',
 'A_FM_1',
 'A_FM_2',
 'E_FM_F_1_1',
 'E_FM_F_1_8888',
 'E_FM_F_1_9999',
 'E_FM_SF_2_9999',
 'E_FM_SF_2_8888',
 'E_FM_SF_2_2',
 'E_FM_M_3_3',
 'E_FM_M_3_8888',
 'E_FM_M_3_9999',
 'E_FM_SM_4_9999',
 'E_FM_SM_4_8888',
 'E_FM_SM_4_4',
 'E_FM_GF_5_9999',
 'E_FM_GF_5_8888',
 'E_FM_GF_5_5',
 'E_FM_GM_6_9999',
 'E_FM_GM_6_8888',
 'E_FM_GM_6_6',
 'E_FM_OBS_7_7',
 'E_FM_OBS_7_8888',
 'E_FM_OBS_7_9999',
 'E_FM_YBS_8_9999',
 'E_FM_YBS_8_8888',
 'E_FM_YBS_8_8',
 'E_FM_NO_9_9999',
 'E_FM_NO_9_8888',
 'E_FM_NO_9_9',
 'E_LT_F_1',
 'E_LT_F_8888',
 'E_LT_F_9999',
 'E_LT_F_2',
 'E_LT_SF_9999',
 'E_LT_SF_8888',
 'E_LT_SF_2',
 'E_LT_SF_1',
 'E_LT_M_1',
 'E_LT_M_8888',
 'E_LT_M_9999',
 'E_LT_M_2',
 'E_LT_SM_9999',
 'E_LT_SM_8888',
 'E_LT_SM_1',
 'E_LT_SM_2',
 'E_EDU_F_3',
 'E_EDU_F_8888',
 'E_EDU_F_2',
 'E_EDU_F_4',
 'E_EDU_F_9999',
 'E_EDU_F_1',
 'E_KRN_F_1',
 'E_KRN_F_8888',
 'E_KRN_F_9999',
 'E_KRN_F_2',
 'E_BORN_F_9999',
 'E_BORN_F_8888',
 'E_BORN_F_6',
 'E_BORN_F_13',
 'E_BORN_F_1',
 'E_BORN_F_2',
 'E_BORN_F_3',
 'E_BORN_F_11',
 'E_BORN_F_10',
 'E_BORN_F_8',
 'E_EDU_M_3',
 'E_EDU_M_8888',
 'E_EDU_M_2',
 'E_EDU_M_4',
 'E_EDU_M_9999',
 'E_EDU_M_1',
 'E_KRN_M_1',
 'E_KRN_M_8888',
 'E_KRN_M_9999',
 'E_KRN_M_2',
 'E_BORN_M_9999',
 'E_BORN_M_8888',
 'E_BORN_M_5',
 'E_BORN_M_6',
 'E_BORN_M_4',
 'E_BORN_M_1',
 'E_BORN_M_2',
 'E_BORN_M_10',
 'E_BORN_M_13',
 'E_BORN_M_8',
 'E_BORN_M_9',
 'E_BORN_M_12',
 'E_BORN_M_3',
 'E_BORN_M_11',
 'E_BORN_M_7',
 'SleepAvg_WK_8',
 'SleepAvg_WK_5',
 'SleepAvg_WK_14',
 'SleepAvg_WK_7',
 'SleepAvg_WK_19',
 'SleepAvg_WK_6',
 'SleepAvg_WK_4',
 'SleepAvg_WK_10',
 'SleepAvg_WK_9',
 'SleepAvg_WK_20',
 'SleepAvg_WK_13',
 'SleepAvg_WK_12',
 'SleepAvg_WK_18',
 'SleepAvg_WK_11',
 'SleepAvg_WK_17',
 'SleepAvg_WK_0',
 'SleepAvg_WK_15',
 'SleepAvg_WK_3',
 'SleepAvg_WK_16',
 'SleepAvg_WK_1',
 'SleepAvg_WK_2']

# Vocab 들을 각각 BMI_1과 코사인 유사도 구하기

In [22]:
#cos는 위의 단어장들 목록들을 가지고 코사인 유사도 구한 결과 저장
cos = []
for col in cols:
    cos.append(model_sg.wv.similarity(col, 'BMI_1')) #절댓값 씌우려면 여기 abs(model_cbow.wv ~~ ) 해주면 됨

In [23]:
#앞에서 구한 vocab들과 코사인 유사도 결과 concat. 
temp_df = pd.concat([pd.Series(cols), pd.Series(cos)], axis = 1)
temp_df = temp_df.sort_values(by=1, ascending = False)
temp_df.reset_index(drop = True, inplace = True)
temp_df.index

RangeIndex(start=0, stop=726, step=1)

In [24]:
temp_df

                 0         1
0            BMI_1  1.000000
1            BMI_0  0.824406
2        O_SYMP5_0  0.814892
3      TC_HTP_MN_0  0.810570
4        O_SYMP1_0  0.808048
..             ...       ...
721        DR_LT_2  0.114439
722    E_BORN_M_11  0.110889
723        DR_LT_3  0.109252
724  E_BORN_M_8888  0.102753
725     E_BORN_F_1  0.099292

[726 rows x 2 columns]

# Vocab 들을 각각 BMI_0과 코사인 유사도 구하기

In [25]:
#cos는 위의 단어장들 목록들을 가지고 코사인 유사도 구한 결과 저장
cos2 = []
for col in cols:
    cos2.append(model_sg.wv.similarity(col, 'BMI_0')) #절댓값 씌우려면 여기 abs(model_cbow.wv ~~ ) 해주면 됨

In [26]:
#앞에서 구한 vocab들과 코사인 유사도 결과 concat. 
temp_df2 = pd.concat([pd.Series(cols), pd.Series(cos2)], axis = 1)
temp_df2 = temp_df2.sort_values(by=1, ascending = False)
temp_df2.reset_index(drop = True, inplace = True)
temp_df2.index

RangeIndex(start=0, stop=726, step=1)

In [27]:
temp_df2

               0         1
0          BMI_0  1.000000
1      O_SYMP4_0  0.896810
2      O_SYMP5_0  0.891793
3      O_SYMP2_0  0.886170
4        V_TRT_1  0.873418
..           ...       ...
721      DR_LT_3  0.117449
722   E_BORN_M_3  0.083531
723   E_BORN_F_6  0.079133
724   E_BORN_F_1  0.062943
725  E_BORN_F_10  0.060608

[726 rows x 2 columns]

## Voccab들을 각각 BMI_1, BMI_0과 유클리디언 거리 구해서 클러스터링 하기
### 센트로이드는 BMI_1, BMI_0 Vocab들을 전부 센트로이드들이랑 유클리디언 거리를 구하고, 둘 중 가까운 곳으로 할당

In [28]:
# c1은 비만 Yes인 클러스터, c2는 비만 No인 클러스터
def vec_means(cols, model):
    c1 = model.wv['BMI_1']
    c2 = model.wv['BMI_0']
    c1_cluster = []
    c2_cluster = []
    for col in cols:
        temp = []
        if np.linalg.norm(c1 - model.wv[col]) > np.linalg.norm(c2 - model.wv[col]): #거리가 더 짧은 센트로이드에 할당이므로
            temp.append(col)
            temp.append(np.linalg.norm(c2 - model.wv[col]))
            c2_cluster.append(temp)
        else:
            temp.append(col)
            temp.append(np.linalg.norm(c1 - model.wv[col]))
            c1_cluster.append(temp)
            
    return c1_cluster, c2_cluster

In [29]:
c1_c , c2_c = vec_means(cols, model_sg)

In [30]:
c1_c = pd.DataFrame(c1_c)
c2_c = pd.DataFrame(c2_c)

In [31]:
c1_c.columns = ['Variables', 'Euclidean distance']
c2_c.columns = ['Variables', 'Euclidean distance']

In [32]:
c1_c = c1_c.sort_values(by = 'Euclidean distance')
c2_c = c2_c.sort_values(by = 'Euclidean distance')

### 비만 Yes인 클러스터

In [33]:
c1_c

      Variables  Euclidean distance
56        BMI_1            0.000000
54    O_DC_FQ_1            0.875419
45      M_SAD_2            0.944092
52   O_BR_SLP_2            1.056326
69    AC_DAYS_1            1.066156
..          ...                 ...
149   E_EDU_M_4            3.894530
79    TC_DAGE_1            4.163774
148   E_EDU_M_2            4.215477
139   E_KRN_F_1            4.320138
147   E_EDU_M_3            5.318131

[161 rows x 2 columns]

In [34]:
c1_c.shape

(161, 2)

### 비만 No인 클러스터

In [35]:
c2_c

         Variables  Euclidean distance
272          BMI_0            0.000000
249      O_SYMP4_0            0.567408
251      O_SYMP5_0            0.580149
245      O_SYMP2_0            0.604471
314        V_TRT_1            0.625370
..             ...                 ...
536  E_BORN_M_9999            8.227446
533   E_EDU_M_8888            8.546662
548  SleepAvg_WK_7            9.620975
535   E_KRN_M_8888           10.809184
537  E_BORN_M_8888           14.664798

[565 rows x 2 columns]

In [36]:
c2_c.head(11)

       Variables  Euclidean distance
272        BMI_0            0.000000
249    O_SYMP4_0            0.567408
251    O_SYMP5_0            0.580149
245    O_SYMP2_0            0.604471
314      V_TRT_1            0.625370
219  O_OCP2_9999            0.629224
339  AC_ACCESS_1            0.643602
333    AC_AMNT_0            0.645689
247    O_SYMP3_0            0.646385
218  O_OCP1_9999            0.658875
241    O_SYMP1_0            0.661204

In [37]:
c1_c.to_csv('BMI_Yes_cluster_ws_156.csv')
c2_c.to_csv('BMI_No_cluster_ws_156.csv')

In [38]:
c1_c.reset_index(drop=True, inplace = True)

In [39]:
c2_c.reset_index(drop=True, inplace = True)

In [40]:
pd.concat([c1_c,c2_c],axis = 1)

      Variables  Euclidean distance      Variables  Euclidean distance
0         BMI_1            0.000000          BMI_0            0.000000
1     O_DC_FQ_1            0.875419      O_SYMP4_0            0.567408
2       M_SAD_2            0.944092      O_SYMP5_0            0.580149
3    O_BR_SLP_2            1.056326      O_SYMP2_0            0.604471
4     AC_DAYS_1            1.066156        V_TRT_1            0.625370
..          ...                 ...            ...                 ...
560         NaN                 NaN  E_BORN_M_9999            8.227446
561         NaN                 NaN   E_EDU_M_8888            8.546662
562         NaN                 NaN  SleepAvg_WK_7            9.620975
563         NaN                 NaN   E_KRN_M_8888           10.809184
564         NaN                 NaN  E_BORN_M_8888           14.664798

[565 rows x 4 columns]

In [41]:
abc = pd.concat([c1_c,c2_c],axis = 1)

In [42]:
abc

      Variables  Euclidean distance      Variables  Euclidean distance
0         BMI_1            0.000000          BMI_0            0.000000
1     O_DC_FQ_1            0.875419      O_SYMP4_0            0.567408
2       M_SAD_2            0.944092      O_SYMP5_0            0.580149
3    O_BR_SLP_2            1.056326      O_SYMP2_0            0.604471
4     AC_DAYS_1            1.066156        V_TRT_1            0.625370
..          ...                 ...            ...                 ...
560         NaN                 NaN  E_BORN_M_9999            8.227446
561         NaN                 NaN   E_EDU_M_8888            8.546662
562         NaN                 NaN  SleepAvg_WK_7            9.620975
563         NaN                 NaN   E_KRN_M_8888           10.809184
564         NaN                 NaN  E_BORN_M_8888           14.664798

[565 rows x 4 columns]

In [44]:
abc.to_csv('BMI_total_ws_156.csv')