In [1]:
import pandas as pd

In [2]:
# 데이터셋 불러오기
df_og = pd.read_csv('kyrbs2019_boy.csv')
df_og.drop('Unnamed: 0', axis = 1, inplace=True)
df_og

,PR_HT,F_BR,F_FRUIT,F_SODA,F_CAFFEINE,F_SWDRINK,F_FASTFOOD,F_VEG,F_MILK,F_EDU,...,E_LT_M,E_LT_SM,E_EDU_F,E_KRN_F,E_BORN_F,E_EDU_M,E_KRN_M,E_BORN_M,SleepAvg_WK,BMI
0,4.0,2.0,3.0,2.0,1.0,2.0,3.0,2.0,2.0,2.0,...,1.0,9999.0,3.0,1.0,9999.0,3.0,1.0,9999.0,8.0,0.0
1,3.0,4.0,7.0,3.0,1.0,1.0,1.0,1.0,4.0,2.0,...,8888.0,8888.0,8888.0,8888.0,8888.0,8888.0,8888.0,8888.0,5.0,0.0
2,1.0,1.0,7.0,1.0,1.0,1.0,2.0,3.0,2.0,1.0,...,1.0,9999.0,2.0,1.0,9999.0,3.0,1.0,9999.0,14.0,1.0
3,3.0,4.0,6.0,1.0,1.0,1.0,1.0,6.0,3.0,1.0,...,8888.0,8888.0,8888.0,8888.0,8888.0,8888.0,8888.0,8888.0,7.0,1.0
4,1.0,8.0,6.0,2.0,2.0,2.0,1.0,7.0,3.0,2.0,...,8888.0,8888.0,8888.0,8888.0,8888.0,8888.0,8888.0,8888.0,19.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27695,1.0,1.0,2.0,1.0,1.0,2.0,1.0,7.0,5.0,1.0,...,1.0,9999.0,4.0,1.0,9999.0,4.0,2.0,5.0,10.0,1.0
27696,3.0,7.0,2.0,1.0,2.0,2.0,3.0,4.0,5.0,2.0,...,8888.0,8888.0,8888.0,8888.0,8888.0,8888.0,8888.0,8888.0,8.0,0.0
27697,2.0,8.0,3.0,2.0,2.0,4.0,2.0,4.0,5.0,1.0,...,1.0,9999.0,2.0,1.0,9999.0,2.0,1.0,9999.0,8.0,1.0
27698,1.0,8.0,2.0,2.0,1.0,2.0,2.0,2.0,4.0,1.0,...,1.0,9999.0,2.0,1.0,9999.0,2.0,1.0,9999.0,8.0,0.0
27699,2.0,1.0,2.0,5.0,2.0,5.0,2.0,2.0,5.0,1.0,...,1.0,9999.0,3.0,1.0,9999.0,3.0,1.0,9999.0,7.0,0.0

In [10]:
variables = ["WC_MN_M03"   ,"WC_MN"     ,  "WC_MN_M10"   ,"GRADE"     ,  "AGE"      ,   "PR_HT" ,      "F_WAT"    ,   "WC_MN_M08"  , "WC_MN_M05"  , "WC_MN_M02"  ,
"WC_MN_M04"  , "TC_ACCESS"  , "WC_MN_M07"  , "E_EDU_M" ,    "E_EDU_F"   ,  "WC_MN_M06"  , "TC_DAYS"  ,   "WC_MN_M09"  , "WC_MN_M01"  , "AC_AMNT"    ,
 "TC_SND_H"   , "AC_FAGE"  ,   "AC_ACCESS" ,  "E_BORN_M"  ,  "INT_WK_MM" ,  "E_LT_F"      ,"PA_SWK_N"   , "TC_FAGE"  ,   "HW_SPRM_H" ,  "O_BR_SLP"   ,
"PA_SWD_S"  ,  "PA_SWK_S"  ,  "TC_SND_S" ,   "E_LT_M"  ,    "TC_AMNT"  ,   "E_KRN_F"    , "TC_LT"   ,    "M_SLP_EN" ,   "HW_SPML_S" ,  "SleepAvg_WK",
"AC_DRUNK"  ,  "E_FM_GF_5"  , "PA_VIG"   ,   "E_FM_OBS_7" , "INT_WD_MM"  , "E_FM_GM_6"   ,"TC_SND_P" ,   "TC_GHW_H"  ,  "E_S_RCRD"   , "PA_MSC"   ,  
"E_KRN_M"   ,  "M_SUI_PLN",   "TC_EC_MN"  ,  "E_FM_M_3"  ,  "O_BR_FQ"  ,   "AS_DG_YR"   , "HW_SPML_H"  , "AC_DAYS"   ,  "E_SES"   ,    "HW_SPRM_S"  ,
 "TC_QT_YR"  ,  "AC_LT"  ,     "F_CS_F06"  ,  "F_CS_F07"  ,  "PA_SWD_N"  ,  "PA_ST"   ,    "S_SI"  ,      "S_EDU"   ,    "F_FRUIT"  ,   "I_SB_BK"   , 
"TC_HTP_MN" ,  "E_FM_F_1"  ,  "PA_TOT"  ,    "HW_SPGO_H"  , "PA_PE_FQ" ,   "TC_HTP_LT"  , "F_VEG"    ,   "TC_EC_LT"  ,  "F_BR"   ,     "PA_WLK"    , 
"INT_WK"  ,    "I_SB_EX"  ,   "E_LT_SM"   ,  "O_SYMP6"   ,  "TC_GHW_QT" ,  "F_CS_F12"    ,"M_STR"   ,    "V_TRT"    ,   "M_SUI_CON"  , "M_SAD"     , 
"F_SWDRINK" ,  "E_FM_SF_2" ,  "O_BR_S"  ,    "TC_DAGE"  ,   "O_SCL"   ,    "E_LT_SF"   ,  "INT_WD"   ,   "PA_TRA_MM"  , "F_CS_F04"  ,  "F_CAFFEINE" ,
"PR_OH"   ,    "A_FM"   ,     "E_FM_YBS_8" , "O_OCP4"   ,   "M_SUI_ATT" ,  "I_SCH_ED1"  , "F_CS"   ,     "TC_GHW"  ,    "S_CONT"   ,   "I_SB_FR"    ,
"E_RES"    ,   "O_SYMP3"  ,   "F_CS_F09" ,   "O_DC_FQ" ,    "F_FASTFOOD"  ,"E_BORN_F"    ,"F_SODA"   ,   "O_OCP5"   ,   "PA_TRA"  ,    "I_SCH_ED2"  ,
"O_EDU"    ,   "E_FM_SM_4"  , "AS_DG_LT"  ,  "ECZ_DG_YR"  , "I_SCH_ED3" ,  "DR_LT"   ,    "O_OCP1"    ,  "E_FM_NO_9" ,  "I_SCH_TRT"  , "O_OCP3"   ,  
"I_SCH_ED5"  , "HW_S_R"   ,   "F_CS_F02"  ,  "O_SYMP5"  ,   "F_MILK"   ,   "O_SYMP4"  ,   "F_CS_F03"   , "F_CS_F05"  ,  "S_CONT_M"  ,  "PA_WLK_MM"  ,
"O_SYMP1"  ,   "O_SYMP1_1" ,  "F_EDU"   ,    "RH_DG_YR"  ,  "F_CS_F11"  ,  "O_SYMP2"    , "F_CS_F10"  ,  "DR_EXP"   ,   "O_OCP2"   ,   "F_CS_F01" ,  
"O_SLNT"   ,   "HW_EDU"   ,   "RH_DG_LT"  ,  "I_SCH_ED4" ,  "ECZ_DG_LT"  , "F_CS_F08"
]

In [11]:
variables

['WC_MN_M03',
 'WC_MN',
 'WC_MN_M10',
 'GRADE',
 'AGE',
 'PR_HT',
 'F_WAT',
 'WC_MN_M08',
 'WC_MN_M05',
 'WC_MN_M02',
 'WC_MN_M04',
 'TC_ACCESS',
 'WC_MN_M07',
 'E_EDU_M',
 'E_EDU_F',
 'WC_MN_M06',
 'TC_DAYS',
 'WC_MN_M09',
 'WC_MN_M01',
 'AC_AMNT',
 'TC_SND_H',
 'AC_FAGE',
 'AC_ACCESS',
 'E_BORN_M',
 'INT_WK_MM',
 'E_LT_F',
 'PA_SWK_N',
 'TC_FAGE',
 'HW_SPRM_H',
 'O_BR_SLP',
 'PA_SWD_S',
 'PA_SWK_S',
 'TC_SND_S',
 'E_LT_M',
 'TC_AMNT',
 'E_KRN_F',
 'TC_LT',
 'M_SLP_EN',
 'HW_SPML_S',
 'SleepAvg_WK',
 'AC_DRUNK',
 'E_FM_GF_5',
 'PA_VIG',
 'E_FM_OBS_7',
 'INT_WD_MM',
 'E_FM_GM_6',
 'TC_SND_P',
 'TC_GHW_H',
 'E_S_RCRD',
 'PA_MSC',
 'E_KRN_M',
 'M_SUI_PLN',
 'TC_EC_MN',
 'E_FM_M_3',
 'O_BR_FQ',
 'AS_DG_YR',
 'HW_SPML_H',
 'AC_DAYS',
 'E_SES',
 'HW_SPRM_S',
 'TC_QT_YR',
 'AC_LT',
 'F_CS_F06',
 'F_CS_F07',
 'PA_SWD_N',
 'PA_ST',
 'S_SI',
 'S_EDU',
 'F_FRUIT',
 'I_SB_BK',
 'TC_HTP_MN',
 'E_FM_F_1',
 'PA_TOT',
 'HW_SPGO_H',
 'PA_PE_FQ',
 'TC_HTP_LT',
 'F_VEG',
 'TC_EC_LT',
 'F_BR',
 'PA_WLK',
 'INT_WK',
 'I_SB_EX',
 'E_LT_SM',
 'O_SYMP6',
 'TC_GHW_QT',
 'F_CS_F12',
 'M_STR',
 'V_TRT',
 'M_SUI_CON',
 'M_SAD',
 'F_SWDRINK',
 'E_FM_SF_2',
 'O_BR_S',
 'TC_DAGE',
 'O_SCL',
 'E_LT_SF',
 'INT_WD',
 'PA_TRA_MM',
 'F_CS_F04',
 'F_CAFFEINE',
 'PR_OH',
 'A_FM',
 'E_FM_YBS_8',
 'O_OCP4',
 'M_SUI_ATT',
 'I_SCH_ED1',
 'F_CS',
 'TC_GHW',
 'S_CONT',
 'I_SB_FR',
 'E_RES',
 'O_SYMP3',
 'F_CS_F09',
 'O_DC_FQ',
 'F_FASTFOOD',
 'E_BORN_F',
 'F_SODA',
 'O_OCP5',
 'PA_TRA',
 'I_SCH_ED2',
 'O_EDU',
 'E_FM_SM_4',
 'AS_DG_LT',
 'ECZ_DG_YR',
 'I_SCH_ED3',
 'DR_LT',
 'O_OCP1',
 'E_FM_NO_9',
 'I_SCH_TRT',
 'O_OCP3',
 'I_SCH_ED5',
 'HW_S_R',
 'F_CS_F02',
 'O_SYMP5',
 'F_MILK',
 'O_SYMP4',
 'F_CS_F03',
 'F_CS_F05',
 'S_CONT_M',
 'PA_WLK_MM',
 'O_SYMP1',
 'O_SYMP1_1',
 'F_EDU',
 'RH_DG_YR',
 'F_CS_F11',
 'O_SYMP2',
 'F_CS_F10',
 'DR_EXP',
 'O_OCP2',
 'F_CS_F01',
 'O_SLNT',
 'HW_EDU',
 'RH_DG_LT',
 'I_SCH_ED4',
 'ECZ_DG_LT',
 'F_CS_F08']

In [12]:
print(len(variables))

156

In [13]:
df = df_og.copy()

In [15]:
df_mda = df.loc[:,variables]

In [16]:
df_mda

,WC_MN_M03,WC_MN,WC_MN_M10,GRADE,AGE,PR_HT,F_WAT,WC_MN_M08,WC_MN_M05,WC_MN_M02,...,F_CS_F10,DR_EXP,O_OCP2,F_CS_F01,O_SLNT,HW_EDU,RH_DG_LT,I_SCH_ED4,ECZ_DG_LT,F_CS_F08
0,0.0,3.0,0.0,4.0,16.0,4.0,5.0,0.0,0.0,0.0,...,10.0,1.0,9999.0,9999.0,1.0,1.0,1.0,9999.0,1.0,9999.0
1,9999.0,1.0,9999.0,4.0,15.0,3.0,3.0,9999.0,9999.0,9999.0,...,10.0,1.0,2.0,1.0,1.0,1.0,1.0,9999.0,1.0,9999.0
2,1.0,4.0,0.0,4.0,16.0,1.0,3.0,0.0,0.0,0.0,...,9999.0,1.0,9999.0,1.0,1.0,1.0,1.0,9999.0,1.0,9999.0
3,1.0,2.0,0.0,4.0,15.0,3.0,5.0,0.0,0.0,1.0,...,9999.0,1.0,9999.0,1.0,1.0,1.0,1.0,9999.0,1.0,8.0
4,1.0,2.0,0.0,4.0,16.0,1.0,5.0,0.0,0.0,0.0,...,9999.0,1.0,9999.0,9999.0,1.0,1.0,1.0,9999.0,1.0,9999.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27695,0.0,2.0,0.0,3.0,14.0,1.0,2.0,0.0,0.0,0.0,...,9999.0,1.0,9999.0,9999.0,1.0,1.0,1.0,4.0,1.0,9999.0
27696,0.0,3.0,0.0,3.0,14.0,3.0,2.0,0.0,0.0,0.0,...,9999.0,1.0,9999.0,9999.0,1.0,1.0,1.0,9999.0,2.0,9999.0
27697,0.0,4.0,0.0,3.0,15.0,2.0,3.0,0.0,0.0,0.0,...,9999.0,1.0,9999.0,9999.0,1.0,1.0,2.0,9999.0,2.0,9999.0
27698,0.0,2.0,0.0,3.0,15.0,1.0,5.0,0.0,0.0,0.0,...,9999.0,1.0,9999.0,9999.0,2.0,1.0,2.0,4.0,1.0,9999.0
27699,0.0,4.0,0.0,3.0,14.0,2.0,4.0,0.0,0.0,0.0,...,9999.0,1.0,2.0,9999.0,1.0,1.0,1.0,9999.0,1.0,9999.0

In [17]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
# 다중공선성 확인
def check_vif(df):
    global vif
    vif = pd.DataFrame()
    vif["VIF Factor"] = [variance_inflation_factor(
        df.values, i) for i in range(df.shape[1])]
    vif["features"] = df.columns

In [18]:
# df_mda 에서 VIF 확인 후 변수 제거
for i in range(1000):
    check_vif(df_mda)
    if len(vif[vif['VIF Factor'] >=10]) >=1:
        remove_col = vif[vif['VIF Factor'] >=10].sort_values('VIF Factor', ascending=False).iloc[0,1]
        df_mda.drop(remove_col, axis=1, inplace=True)
        print('제거된 변수는', remove_col)
    else:
        display(vif)
        break

C:\Users\SeongHee\Anaconda3\lib\site-packages\statsmodels\stats\outliers_influence.py:193: RuntimeWarning: divide by zero encountered in double_scalars
  vif = 1. / (1. - r_squared_i)

제거된 변수는 E_KRN_M

C:\Users\SeongHee\Anaconda3\lib\site-packages\statsmodels\stats\outliers_influence.py:193: RuntimeWarning: divide by zero encountered in double_scalars
  vif = 1. / (1. - r_squared_i)

제거된 변수는 E_KRN_F
제거된 변수는 E_FM_SM_4
제거된 변수는 E_FM_SF_2
제거된 변수는 WC_MN_M06
제거된 변수는 WC_MN_M04
제거된 변수는 WC_MN_M05
제거된 변수는 WC_MN_M07
제거된 변수는 ECZ_DG_LT
제거된 변수는 WC_MN_M08
제거된 변수는 RH_DG_LT
제거된 변수는 E_FM_M_3
제거된 변수는 WC_MN_M10
제거된 변수는 WC_MN_M02
제거된 변수는 E_FM_F_1
제거된 변수는 TC_GHW
제거된 변수는 WC_MN_M09
제거된 변수는 WC_MN_M03
제거된 변수는 E_EDU_M
제거된 변수는 E_EDU_F
제거된 변수는 TC_GHW_QT
제거된 변수는 S_SI
제거된 변수는 AGE
제거된 변수는 E_FM_NO_9
제거된 변수는 DR_EXP
제거된 변수는 E_BORN_F
제거된 변수는 AS_DG_LT
제거된 변수는 TC_FAGE
제거된 변수는 E_LT_SM
제거된 변수는 A_FM
제거된 변수는 TC_DAGE
제거된 변수는 M_SUI_ATT
제거된 변수는 E_BORN_M
제거된 변수는 E_LT_SF
제거된 변수는 F_CS_F09
제거된 변수는 TC_HTP_LT
제거된 변수는 S_CONT_M
제거된 변수는 TC_QT_YR
제거된 변수는 M_SUI_PLN
제거된 변수는 F_CS_F02
제거된 변수는 INT_WK
제거된 변수는 AC_LT
제거된 변수는 TC_EC_LT
제거된 변수는 TC_LT
제거된 변수는 INT_WD
제거된 변수는 AC_FAGE
제거된 변수는 S_EDU
제거된 변수는 F_CS_F08
제거된 변수는 M_SUI_CON
제거된 변수는 F_CS_F11
제거된 변수는 O_OCP4
제거된 변수는 S_CONT
제거된 변수는 I_SCH_ED1
제거된 변수는 F_CS_F06
제거된 변수는 HW_EDU
제거된 변수는 PA_WLK
제거된 변수는 PR_OH
제거된 변수는 F_WAT
제거된 변수는 WC_MN
제거된 변수는 I_SB_BK
제거된 변수는 PA_PE_FQ
제거된 변수는 O_SCL
제거된 변수는 F_CS_F05
제거된 변수는 F_EDU
제거된 변수는 E_FM_GF_5
제거된 변수는 M_STR
제거된 변수는 HW_SPML_S
제거된 변수는 HW_SPRM_H
제거된 변수는 M_SAD
제거된 변수는 O_BR_SLP
제거된 변수는 O_SLNT
제거된 변수는 E_SES
제거된 변수는 M_SLP_EN

    VIF Factor   features
0     8.082846      GRADE
1     6.900528      PR_HT
2     9.112036  TC_ACCESS
3     7.395202    TC_DAYS
4     2.205685  WC_MN_M01
..         ...        ...
78    1.764308    O_SYMP2
79    7.014533   F_CS_F10
80    7.380602     O_OCP2
81    7.033948   F_CS_F01
82    4.010928  I_SCH_ED4

[83 rows x 2 columns]

In [19]:
vif.features.tolist()

['GRADE',
 'PR_HT',
 'TC_ACCESS',
 'TC_DAYS',
 'WC_MN_M01',
 'AC_AMNT',
 'TC_SND_H',
 'AC_ACCESS',
 'INT_WK_MM',
 'E_LT_F',
 'PA_SWK_N',
 'PA_SWD_S',
 'PA_SWK_S',
 'TC_SND_S',
 'E_LT_M',
 'TC_AMNT',
 'SleepAvg_WK',
 'AC_DRUNK',
 'PA_VIG',
 'E_FM_OBS_7',
 'INT_WD_MM',
 'E_FM_GM_6',
 'TC_SND_P',
 'TC_GHW_H',
 'E_S_RCRD',
 'PA_MSC',
 'TC_EC_MN',
 'O_BR_FQ',
 'AS_DG_YR',
 'HW_SPML_H',
 'AC_DAYS',
 'HW_SPRM_S',
 'F_CS_F07',
 'PA_SWD_N',
 'PA_ST',
 'F_FRUIT',
 'TC_HTP_MN',
 'PA_TOT',
 'HW_SPGO_H',
 'F_VEG',
 'F_BR',
 'I_SB_EX',
 'O_SYMP6',
 'F_CS_F12',
 'V_TRT',
 'F_SWDRINK',
 'O_BR_S',
 'PA_TRA_MM',
 'F_CS_F04',
 'F_CAFFEINE',
 'E_FM_YBS_8',
 'F_CS',
 'I_SB_FR',
 'E_RES',
 'O_SYMP3',
 'O_DC_FQ',
 'F_FASTFOOD',
 'F_SODA',
 'O_OCP5',
 'PA_TRA',
 'I_SCH_ED2',
 'O_EDU',
 'ECZ_DG_YR',
 'I_SCH_ED3',
 'DR_LT',
 'O_OCP1',
 'I_SCH_TRT',
 'O_OCP3',
 'I_SCH_ED5',
 'HW_S_R',
 'O_SYMP5',
 'F_MILK',
 'O_SYMP4',
 'F_CS_F03',
 'PA_WLK_MM',
 'O_SYMP1',
 'O_SYMP1_1',
 'RH_DG_YR',
 'O_SYMP2',
 'F_CS_F10',
 'O_OCP2',
 'F_CS_F01',
 'I_SCH_ED4']

In [23]:
len(vif.features.tolist()[:37])

37

In [24]:
# df_min_ED에서 VIF 확인 후 살아남은 변수들 + 비만 여부 변수 ( Target Attribute )만 다시 df에서 뽑아서 df_min_ED에 할당
df_mda = df[vif.features.tolist()[:37] + ['BMI']]

In [25]:
df_mda

,GRADE,PR_HT,TC_ACCESS,TC_DAYS,WC_MN_M01,AC_AMNT,TC_SND_H,AC_ACCESS,INT_WK_MM,E_LT_F,...,AS_DG_YR,HW_SPML_H,AC_DAYS,HW_SPRM_S,F_CS_F07,PA_SWD_N,PA_ST,F_FRUIT,TC_HTP_MN,BMI
0,4.0,4.0,5.0,7.0,0.0,4.0,1.0,5.0,4.0,1.0,...,0.0,2.0,4.0,1.0,7.0,4.0,1.0,3.0,0.0,0.0
1,4.0,3.0,1.0,7.0,9999.0,0.0,1.0,1.0,0.0,8888.0,...,0.0,1.0,0.0,1.0,9999.0,5.0,3.0,7.0,1.0,0.0
2,4.0,1.0,1.0,0.0,1.0,0.0,4.0,1.0,5.0,1.0,...,0.0,1.0,0.0,1.0,7.0,3.0,2.0,7.0,0.0,1.0
3,4.0,3.0,1.0,0.0,1.0,0.0,1.0,1.0,8.0,8888.0,...,0.0,2.0,1.0,1.0,9999.0,3.0,1.0,6.0,0.0,1.0
4,4.0,1.0,1.0,0.0,1.0,0.0,3.0,1.0,4.0,8888.0,...,0.0,2.0,0.0,2.0,9999.0,1.0,1.0,6.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27695,3.0,1.0,1.0,0.0,1.0,0.0,8.0,1.0,0.0,1.0,...,0.0,1.0,0.0,1.0,9999.0,0.0,2.0,2.0,0.0,1.0
27696,3.0,3.0,1.0,0.0,0.0,0.0,2.0,1.0,0.0,8888.0,...,0.0,2.0,1.0,1.0,9999.0,1.0,1.0,2.0,0.0,0.0
27697,3.0,2.0,1.0,0.0,1.0,0.0,1.0,1.0,10.0,1.0,...,0.0,3.0,0.0,4.0,9999.0,3.0,2.0,3.0,0.0,1.0
27698,3.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,10.0,1.0,...,0.0,3.0,0.0,3.0,9999.0,3.0,3.0,2.0,0.0,0.0
27699,3.0,2.0,1.0,0.0,1.0,0.0,1.0,1.0,2.0,1.0,...,0.0,3.0,0.0,1.0,7.0,1.0,5.0,2.0,0.0,0.0

In [26]:
# 데이터 저장
df_mda.to_csv('df_mda.csv')